version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"
    cooldown:
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 14

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
